# Generated by Django 4.2 on 2024-11-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('last_questionnaire', models.DateTimeField(blank=True, null=True)),
                ('preferences', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mood', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('anxiety_level', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('social_level', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('energy_level', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('stress_level', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('sleep_quality', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('appetite', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('focus_level', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('motivation', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('suicidal_thoughts', models.IntegerField(choices=[(1, 'Muito Mal'), (2, 'Mal'), (3, 'Normal'), (4, 'Bem')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('songs', models.JSONField()),
                ('mood_category', models.CharField(max_length=50)),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
